// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package store

import (
	"context"
	"database/sql"
)

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countItemsStmt, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByUser = `-- name: CountItemsByUser :one
SELECT COUNT(*) FROM items WHERE user_id = ?
`

func (q *Queries) CountItemsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.countItemsByUserStmt, countItemsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, user_id, title, description, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, title, description, status, created_at, updated_at
`

type CreateItemParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.queryRow(ctx, q.createItemStmt, createItem,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteItemStmt, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, title, description, status, created_at, updated_at FROM items WHERE id = ? LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.queryRow(ctx, q.getItemStmt, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, user_id, title, description, status, created_at, updated_at FROM items ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListItemsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.query(ctx, q.listItemsStmt, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByUser = `-- name: ListItemsByUser :many
SELECT id, user_id, title, description, status, created_at, updated_at FROM items WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListItemsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListItemsByUser(ctx context.Context, arg ListItemsByUserParams) ([]Item, error) {
	rows, err := q.query(ctx, q.listItemsByUserStmt, listItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items 
SET title = COALESCE(?, title),
    description = COALESCE(?, description),
    status = COALESCE(?, status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, description, status, created_at, updated_at
`

type UpdateItemParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.queryRow(ctx, q.updateItemStmt, updateItem,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
