// This file is auto-generated by @hey-api/openapi-ts

export const UserSchema = {
    type: 'object',
    required: [
        'id',
        'email',
        'name',
        'role',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier'
        },
        email: {
            type: 'string',
            format: 'email',
            description: 'User email address'
        },
        name: {
            type: 'string',
            description: 'User full name'
        },
        role: {
            type: 'string',
            enum: [
                'admin',
                'user'
            ],
            description: 'User role'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            description: 'Creation timestamp'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            description: 'Last update timestamp'
        }
    }
} as const;

export const CreateUserRequestSchema = {
    type: 'object',
    required: [
        'email',
        'name'
    ],
    properties: {
        email: {
            type: 'string',
            format: 'email',
            description: 'User email address'
        },
        name: {
            type: 'string',
            minLength: 1,
            description: 'User full name'
        },
        role: {
            type: 'string',
            enum: [
                'admin',
                'user'
            ],
            default: 'user',
            description: 'User role'
        }
    }
} as const;

export const UpdateUserRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            description: 'User email address'
        },
        name: {
            type: 'string',
            minLength: 1,
            description: 'User full name'
        },
        role: {
            type: 'string',
            enum: [
                'admin',
                'user'
            ],
            description: 'User role'
        }
    }
} as const;

export const PaginationSchema = {
    type: 'object',
    required: [
        'page',
        'limit',
        'total',
        'totalPages'
    ],
    properties: {
        page: {
            type: 'integer',
            description: 'Current page number'
        },
        limit: {
            type: 'integer',
            description: 'Items per page'
        },
        total: {
            type: 'integer',
            description: 'Total number of items'
        },
        totalPages: {
            type: 'integer',
            description: 'Total number of pages'
        }
    }
} as const;

export const UserListResponseSchema = {
    type: 'object',
    required: [
        'data',
        'pagination'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/User'
            }
        },
        pagination: {
            $ref: '#/components/schemas/Pagination'
        }
    }
} as const;

export const ItemSchema = {
    type: 'object',
    required: [
        'id',
        'userId',
        'title',
        'status',
        'createdAt',
        'updatedAt'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            description: 'Owner user ID'
        },
        title: {
            type: 'string',
            description: 'Item title'
        },
        description: {
            type: 'string',
            description: 'Item description'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'in_progress',
                'completed'
            ],
            description: 'Item status'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            description: 'Creation timestamp'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            description: 'Last update timestamp'
        }
    }
} as const;

export const CreateItemRequestSchema = {
    type: 'object',
    required: [
        'userId',
        'title'
    ],
    properties: {
        userId: {
            type: 'string',
            format: 'uuid',
            description: 'Owner user ID'
        },
        title: {
            type: 'string',
            minLength: 1,
            description: 'Item title'
        },
        description: {
            type: 'string',
            description: 'Item description'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'in_progress',
                'completed'
            ],
            default: 'pending',
            description: 'Item status'
        }
    }
} as const;

export const UpdateItemRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            minLength: 1,
            description: 'Item title'
        },
        description: {
            type: 'string',
            description: 'Item description'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'in_progress',
                'completed'
            ],
            description: 'Item status'
        }
    }
} as const;

export const ItemListResponseSchema = {
    type: 'object',
    required: [
        'data',
        'pagination'
    ],
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Item'
            }
        },
        pagination: {
            $ref: '#/components/schemas/Pagination'
        }
    }
} as const;

export const APIErrorSchema = {
    type: 'object',
    required: [
        'code',
        'message',
        'requestId'
    ],
    properties: {
        code: {
            type: 'string',
            description: 'Error code',
            enum: [
                'VALIDATION_ERROR',
                'NOT_FOUND',
                'CONFLICT',
                'INTERNAL_ERROR',
                'BAD_REQUEST',
                'UNAUTHORIZED'
            ]
        },
        message: {
            type: 'string',
            description: 'Human-readable error message'
        },
        details: {
            description: 'Additional error details'
        },
        requestId: {
            type: 'string',
            description: 'Request ID for tracking'
        }
    }
} as const;
