// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateItemData, CreateItemErrors, CreateItemResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteItemData, DeleteItemErrors, DeleteItemResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetItemData, GetItemErrors, GetItemResponses, GetUserData, GetUserErrors, GetUserResponses, HealthCheckData, HealthCheckResponses, ListItemsData, ListItemsErrors, ListItemsResponses, ListUsersData, ListUsersErrors, ListUsersResponses, UpdateItemData, UpdateItemErrors, UpdateItemResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List users
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({ url: '/api/users', ...options });

/**
 * Create a new user
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({ url: '/api/users/{id}', ...options });

/**
 * Get a user by ID
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/api/users/{id}', ...options });

/**
 * Update a user
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List items
 */
export const listItems = <ThrowOnError extends boolean = false>(options?: Options<ListItemsData, ThrowOnError>) => (options?.client ?? client).get<ListItemsResponses, ListItemsErrors, ThrowOnError>({ url: '/api/items', ...options });

/**
 * Create a new item
 */
export const createItem = <ThrowOnError extends boolean = false>(options: Options<CreateItemData, ThrowOnError>) => (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
    url: '/api/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(options: Options<DeleteItemData, ThrowOnError>) => (options.client ?? client).delete<DeleteItemResponses, DeleteItemErrors, ThrowOnError>({ url: '/api/items/{id}', ...options });

/**
 * Get an item by ID
 */
export const getItem = <ThrowOnError extends boolean = false>(options: Options<GetItemData, ThrowOnError>) => (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>({ url: '/api/items/{id}', ...options });

/**
 * Update an item
 */
export const updateItem = <ThrowOnError extends boolean = false>(options: Options<UpdateItemData, ThrowOnError>) => (options.client ?? client).put<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
    url: '/api/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
