// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type User = {
    /**
     * Unique identifier
     */
    id: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    name: string;
    /**
     * User role
     */
    role: 'admin' | 'user';
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type CreateUserRequest = {
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    name: string;
    /**
     * User role
     */
    role?: 'admin' | 'user';
};

export type UpdateUserRequest = {
    /**
     * User email address
     */
    email?: string;
    /**
     * User full name
     */
    name?: string;
    /**
     * User role
     */
    role?: 'admin' | 'user';
};

export type Pagination = {
    /**
     * Current page number
     */
    page: number;
    /**
     * Items per page
     */
    limit: number;
    /**
     * Total number of items
     */
    total: number;
    /**
     * Total number of pages
     */
    totalPages: number;
};

export type UserListResponse = {
    data: Array<User>;
    pagination: Pagination;
};

export type Item = {
    /**
     * Unique identifier
     */
    id: string;
    /**
     * Owner user ID
     */
    userId: string;
    /**
     * Item title
     */
    title: string;
    /**
     * Item description
     */
    description?: string;
    /**
     * Item status
     */
    status: 'pending' | 'in_progress' | 'completed';
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type CreateItemRequest = {
    /**
     * Owner user ID
     */
    userId: string;
    /**
     * Item title
     */
    title: string;
    /**
     * Item description
     */
    description?: string;
    /**
     * Item status
     */
    status?: 'pending' | 'in_progress' | 'completed';
};

export type UpdateItemRequest = {
    /**
     * Item title
     */
    title?: string;
    /**
     * Item description
     */
    description?: string;
    /**
     * Item status
     */
    status?: 'pending' | 'in_progress' | 'completed';
};

export type ItemListResponse = {
    data: Array<Item>;
    pagination: Pagination;
};

export type ApiError = {
    /**
     * Error code
     */
    code: 'VALIDATION_ERROR' | 'NOT_FOUND' | 'CONFLICT' | 'INTERNAL_ERROR' | 'BAD_REQUEST' | 'UNAUTHORIZED';
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Additional error details
     */
    details?: unknown;
    /**
     * Request ID for tracking
     */
    requestId: string;
};

/**
 * Page number (1-indexed)
 */
export type PageParam = number;

/**
 * Number of items per page
 */
export type LimitParam = number;

/**
 * User ID
 */
export type UserIdParam = string;

/**
 * Item ID
 */
export type ItemIdParam = string;

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Service is healthy
     */
    200: {
        status?: string;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Internal server error
     */
    500: ApiError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * List of users
     */
    200: UserListResponse;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Bad request
     */
    400: ApiError;
    /**
     * Resource conflict
     */
    409: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User created successfully
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User details
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Bad request
     */
    400: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * User updated successfully
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Filter by user ID
         */
        userId?: string;
    };
    url: '/api/items';
};

export type ListItemsErrors = {
    /**
     * Internal server error
     */
    500: ApiError;
};

export type ListItemsError = ListItemsErrors[keyof ListItemsErrors];

export type ListItemsResponses = {
    /**
     * List of items
     */
    200: ItemListResponse;
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type CreateItemData = {
    body: CreateItemRequest;
    path?: never;
    query?: never;
    url: '/api/items';
};

export type CreateItemErrors = {
    /**
     * Bad request
     */
    400: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * Item created successfully
     */
    201: Item;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
    body?: never;
    path: {
        /**
         * Item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type DeleteItemErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
    /**
     * Item deleted successfully
     */
    204: void;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type GetItemData = {
    body?: never;
    path: {
        /**
         * Item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type GetItemErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
    /**
     * Item details
     */
    200: Item;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type UpdateItemData = {
    body: UpdateItemRequest;
    path: {
        /**
         * Item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type UpdateItemErrors = {
    /**
     * Bad request
     */
    400: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
    /**
     * Item updated successfully
     */
    200: Item;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];
